import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientToasts from "./toasts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="border-b bg-white">
          <nav className="container mx-auto flex items-center justify-between py-4">
            <a href="/" className="text-xl font-semibold">
              EVITA Inventory
            </a>
            <div className="flex gap-4">
              <a href="/" className="text-gray-700 hover:text-black">
                Home
              </a>
              <a href="/inventory" className="text-gray-700 hover:text-black">
                Inventory
              </a>
              <a href="/storage" className="text-gray-700 hover:text-black">
                Storage
              </a>
              <a href="/labs" className="text-gray-700 hover:text-black">
                Labs
              </a>
              <a href="/movements" className="text-gray-700 hover:text-black">
                Movements
              </a>
            </div>
          </nav>
        </header>
        <main className="container mx-auto py-6">{children}</main>
        <ClientToasts />
      </body>
    </html>
  );
}
